"""
name: Physical name of that index
can_id: CAN ID on which this data is coming
can_id_start_bit: Start bit of that data point on that CAN ID 
can_id_end_bit: End bit(included) of that data point on that CAN ID
index: What is the index in the output
lower_limit: Lower limit of that value
upper_limit: Upper limit of that value
var_type: What is the variable type should we receive
range: Shows whether we will receive discrete values or continuous values(google it if dont know about discrete and continuous) 
        True if values are continuous, False in case of discrete values
"""

bms_validation = [
    {
        "name": "BMS data Balancing limit",
        "can_id": "110",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 52,
        "lower_limit": 0,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "BMS Data Pre Charge Limit",
        "can_id": "110",
        "can_id_start_bit": 2,
        "can_id_end_bit": 2,
        "roundabout": 0,
        "multiplier": 1,
        "index": 53,
        "lower_limit": 0,
        "upper_limit": 1,
        "range": False,
    },
    {
        "name": "BMS Data Balancing Active",
        "can_id": "110",
        "can_id_start_bit": 3,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 1,
        "index": 54,
        "lower_limit": 0,
        "upper_limit": 1,
        "range": False,
    },
    {
        "name": "BMS Data Pack I Master",
        "can_id": "110",
        "can_id_start_bit": 4,
        "can_id_end_bit": 7,
        "roundabout": 0,
        "multiplier": 0.01,
        "index": 3,
        "lower_limit": -4294967296,
        "upper_limit": 4294967296,
        "range": True,
    },
    {
        "name": "Pack Q SoC Trimmed",
        "can_id": "111",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.01,
        "index": 4,
        "lower_limit": 0,
        "upper_limit": 100,
        "range": True,
    },
    {
        "name": "SOH",
        "can_id": "111",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.01,
        "index": 5,
        "lower_limit": 0,
        "upper_limit": 100,
        "range": True,
    },
    {
        "name": "BMS Status",
        "can_id": "111",
        "can_id_start_bit": 4,
        "can_id_end_bit": 4,
        "roundabout": 0,
        "multiplier": 1,
        "index": 7,
        "lower_limit": 0,
        "upper_limit": 4,
        "range": True,
    },
    {
        "name": "Fully Charge Flag",
        "can_id": "111",
        "can_id_start_bit": 5,
        "can_id_end_bit": 5,
        "roundabout": 0,
        "multiplier": 1,
        "index": 51,
        "lower_limit": 0,
        "upper_limit": 1,
        "range": False,
    },
    {
        "name": "Pack V Sum of Cells",
        "can_id": "111",
        "can_id_start_bit": 6,
        "can_id_end_bit": 7,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 6,
        "lower_limit": 63,
        "upper_limit": 83,
        "range": True,
    },
    {
        "name": "Aux Temperature_1",
        "can_id": "112",
        "can_id_start_bit": 0,
        "can_id_end_bit": 0,
        "roundabout": 0,
        "multiplier": 1,
        "index": 8,
        "lower_limit": 0,
        "upper_limit": 40,
        "range": True,
    },
    {
        "name": "Aux Temperature_2",
        "can_id": "112",
        "can_id_start_bit": 1,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 1,
        "index": 9,
        "lower_limit": 0,
        "upper_limit": 40,
        "range": True,
    },
    {
        "name": "Aux Temperature_3",
        "can_id": "112",
        "can_id_start_bit": 2,
        "can_id_end_bit": 2,
        "roundabout": 0,
        "multiplier": 1,
        "index": 10,
        "lower_limit": 0,
        "upper_limit": 40,
        "range": True,
    },
    {
        "name": "Aux Temperature_4",
        "can_id": "112",
        "can_id_start_bit": 3,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 1,
        "index": 11,
        "lower_limit": 0,
        "upper_limit": 40,
        "range": True,
    },
    {
        "name": "Aux Temperature_5",
        "can_id": "112",
        "can_id_start_bit": 4,
        "can_id_end_bit": 4,
        "roundabout": 0,
        "multiplier": 1,
        "index": 12,
        "lower_limit": 0,
        "upper_limit": 40,
        "range": True,
    },
    {
        "name": "Aux Temperature_6",
        "can_id": "112",
        "can_id_start_bit": 5,
        "can_id_end_bit": 5,
        "roundabout": 0,
        "multiplier": 1,
        "index": 13,
        "lower_limit": 0,
        "upper_limit": 40,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_1",
        "can_id": "113",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 15,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_2",
        "can_id": "113",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 16,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_3",
        "can_id": "113",
        "can_id_start_bit": 4,
        "can_id_end_bit": 5,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 17,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_4",
        "can_id": "113",
        "can_id_start_bit": 6,
        "can_id_end_bit": 7,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 18,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_5",
        "can_id": "114",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 19,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_6",
        "can_id": "114",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 20,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_7",
        "can_id": "114",
        "can_id_start_bit": 4,
        "can_id_end_bit": 5,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 21,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_8",
        "can_id": "114",
        "can_id_start_bit": 6,
        "can_id_end_bit": 7,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 22,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_9",
        "can_id": "115",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 23,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_10",
        "can_id": "115",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 24,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_1",
        "can_id": "116",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 33,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_2",
        "can_id": "116",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 34,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_3",
        "can_id": "116",
        "can_id_start_bit": 4,
        "can_id_end_bit": 5,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 35,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_4",
        "can_id": "116",
        "can_id_start_bit": 6,
        "can_id_end_bit": 7,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 36,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_5",
        "can_id": "117",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 37,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_6",
        "can_id": "117",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 38,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_7",
        "can_id": "117",
        "can_id_start_bit": 4,
        "can_id_end_bit": 5,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 39,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_8",
        "can_id": "117",
        "can_id_start_bit": 6,
        "can_id_end_bit": 7,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 40,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU1 Cell Voltage_9",
        "can_id": "118",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 41,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "CMU2 Cell Voltage_10",
        "can_id": "118",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 42,
        "lower_limit": 3100,
        "upper_limit": 4200,
        "range": True,
    },
    {
        "name": "Dynamic In Limit",
        "can_id": "12a",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 60,
        "lower_limit": 0,
        "upper_limit": 200,
        "range": True,
    },
    {
        "name": "Dynamic Out Limit",
        "can_id": "12a",
        "can_id_start_bit": 2,
        "can_id_end_bit": 3,
        "roundabout": 0,
        "multiplier": 0.1,
        "index": 61,
        "lower_limit": 0,
        "upper_limit": 250,
        "range": True,
    },
    {
        "name": "AC Speed of Compressor",
        "can_id": "248",
        "can_id_start_bit": 0,
        "can_id_end_bit": 1,
        "roundabout": 0,
        "multiplier": 1, 
        "index": 61,  #dumb here
        "lower_limit": 0, #dumb here
        "upper_limit": 250, #dumb here
        "range": True, #dumb here
    },
    {
        "name": "Compressor Run Current",
        "can_id": "248",
        "can_id_start_bit": 6,
        "can_id_end_bit": 6,
        "roundabout": 0,
        "multiplier": 1, 
        "index": 61,  #dumb here
        "lower_limit": 0, #dumb here
        "upper_limit": 250, #dumb here
        "range": True, #dumb here
    },
    {
        "name": "Compressor Run Voltage",
        "can_id": "248",
        "can_id_start_bit": 6,
        "can_id_end_bit": 6,
        "roundabout": 0,
        "multiplier": 1, 
        "index": 61,  #dumb here
        "lower_limit": 0, #dumb here
        "upper_limit": 250, #dumb here
        "range": True, #dumb here
    },
]


